export const CELL = {
    PLAIN: 0,
    HIGHLIGHT : 1,
    AI : 2,
    USER : 3
}

export const MAP = {
    GENERATE_MAP : "GENERATE_MAP",
    CHANGE_DELAY : "CHANGE_DELAY",
    CHANGE_VALUE : "CHANGE_VALUE",
    PREV_CELL    : "PREV_CELL",
    SET_PREV_CELL : "SET_PREV_CELL",
    SETUP_MODES: "SETUP_MODES",
    SET_GAME_MODE: "SET_GAME_MODE",
    SET_GAME_STATE: "SET_GAME_STATE"
}

export const PLAYER = {
    SET_USERNAME : "SET_USERNAME",
    SET_USER_SCORE: "SET_USER_SCORE",
    SET_AI_SCORE: "SET_AI_SCORE",
    RESET_PLAYERS: "RESET_PLAYERS",
    SET_WINNER : "SET_WINNER"
}

export const LEADERS = {
    GET_LEADERS : "GET_LEADERS"
}